# Generated by Django 5.0.4 on 2024-04-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlottedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(db_index=True, max_length=100)),
                ("file_path", models.CharField(max_length=512)),
                ("format", models.CharField(max_length=10)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("enriched_data", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
